version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - prisma-persist:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "development"
      POSTGRES_PASSWORD: "abc123!!!"
    networks:
      file-transfer-automation:
  app:
    build:
      dockerfile: prod.dockerfile
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./download:/app/download
    networks:
      file-transfer-automation:
    restart: on-failure
networks:
  file-transfer-automation:
volumes:
  db-persist:
  prisma-persist:
